# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abstract', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('information', models.TextField(blank=True, default=None, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('source', models.TextField(blank=True, default=None, null=True)),
                ('main_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='research_group.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_group.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151, verbose_name='Nombre')),
                ('prefix', models.CharField(blank=True, choices=[('PHD', 'PhD.'), ('MSC', 'MSc.'), ('ENG', 'Ing.'), ('MAL', 'Sr.'), ('FEM', 'Sra.')], default=None, max_length=3, null=True, verbose_name='Prefijo')),
                ('title', models.TextField(verbose_name='Títulos')),
                ('photo_url', models.URLField(blank=True, default=None, max_length=250, null=True, verbose_name='Fotografía')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_group.Item')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_group.Person'),
        ),
        migrations.AddField(
            model_name='conference',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_group.Item'),
        ),
        migrations.AddField(
            model_name='article',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_group.Item'),
        ),
    ]
