# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
