# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-05 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_group', '0003_auto_20171004_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='object',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='object',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='object',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='object',
            new_name='item',
        ),
    ]
